import { OAuthUserSchema } from "./oauth-user.model";

const GitHubAccountSchema = {
  access_token: { type: String, required: true },
  token_type: { type: String, required: true },
  scope: { type: String, required: true },
  type: { type: String, required: true },
  providerAccountId: { type: String, required: true },
  provider: {
    type: String,
    required: true,
    default: "github",
    enum: ["github"],
  },
};

const GitHubProfileSchema = {
  login: { type: String, required: true },
  id: { type: Number, required: true },
  node_id: { type: String, required: true },
  avatar_url: { type: String, required: true },
  gravatar_id: { type: String },
  url: { type: String, required: true },
  html_url: { type: String, required: true },
  followers_url: { type: String, required: true },
  following_url: { type: String, required: true },
  gists_url: { type: String, required: true },
  starred_url: { type: String, required: true },
  subscriptions_url: { type: String, required: true },
  organizations_url: { type: String, required: true },
  repos_url: { type: String, required: true },
  events_url: { type: String, required: true },
  received_events_url: { type: String, required: true },
  type: { type: String, required: true },
  site_admin: { type: Boolean, required: true },
  name: { type: String },
  company: { type: String },
  blog: { type: String },
  location: { type: String },
  email: { type: String },
  hireable: { type: Boolean },
  bio: { type: String },
  twitter_username: { type: String },
  public_repos: { type: Number, required: true },
  public_gists: { type: Number, required: true },
  followers: { type: Number, required: true },
  following: { type: Number, required: true },
  created_at: { type: String, required: true },
  updated_at: { type: String, required: true },
  private_gists: { type: Number },
  total_private_repos: { type: Number },
  owned_private_repos: { type: Number },
  disk_usage: { type: Number },
  suspended_at: { type: String },
  collaborators: { type: Number },
  two_factor_authentication: { type: Boolean, required: true },
  plan: {
    collaborators: { type: Number },
    name: { type: String },
    space: { type: Number },
    private_repos: { type: Number },
  },
};

export const GitHubAuthUserSchema = {
  user: OAuthUserSchema,
  account: GitHubAccountSchema,
  profile: GitHubProfileSchema,
};
